object_type: global_settings
overrides:
    "aggregate.incrementalUpdate.partition.enabled": "true"
    "tables.create.partitions.maximumEstimatedNumberOfPartitions": 10000
    "aggregate.batch.gracePeriodOverrides.enabled": true
